---
- name: installing tomcat on ubuntu
  hosts: all
  become: yes
  tasks: 
  - name: install java 
    ansible.builtin.apt: 
      name: openjdk-11-jdk
      update_cache: yes 
      state: present
  - name: create group tomcat
    ansible.builtin.group:
      name: tomcat
      state: present
  - name: Add the user 
    ansible.builtin.user:
      name: tomcat
      home: /opt/tomcat
      create_home: yes
      shell: /bin/false
      groups: tomcat
  - name: Download Apache Tomcat
    ansible.builtin.get_url: 
      url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.5/bin/apache-tomcat-10.1.5.tar.gz
      dest: /tmp
  - name: create directory
    ansible.builtin.file:
      path: /opt/tomcat/
      state: directory    
  - name: Extract
    ansible.builtin.unarchive:
      src: /tmp/apache-tomcat-10.1.5.tar.gz
      dest: /opt/tomcat/
      remote_src: yes
  - name: Change file ownership, group and permissions
    ansible.builtin.file:
      path: /opt/tomcat/
      owner: tomcat
      group: tomcat
      recurse: yes
      mode: u+x
  - name: Copy tomcat users file
    ansible.builtin.copy:
      src: /home/raji/tomcat/tomcat-users.xml
      dest: /opt/tomcat/apache-tomcat-10.1.5/conf/tomcat-users.xml
      owner: tomcat
      group: tomcat
  - name: Copy context file in manager folder
    ansible.builtin.copy:
      src: /home/raji/tomcat/context.xml
      dest: /opt/tomcat/apache-tomcat-10.1.5/webapps/manager/META-INF/context.xml
      owner: tomcat
      group: tomcat
  - name: Copy context file in host-manager folder
    ansible.builtin.copy:
      src: /home/raji/tomcat/context.xml
      dest: /opt/tomcat/apache-tomcat-10.1.5/webapps/host-manager/META-INF/context.xml
      owner: tomcat
      group: tomcat
  - name: Copy tomcat service
    ansible.builtin.copy:
      src: /home/raji/tomcat/tomcat.service
      dest: /etc/systemd/system/tomcat.service
      owner: tomcat
      group: tomcat
  - name: Restart daemon-reload 
    ansible.builtin.systemd:
      name: tomcat
      daemon_reload: yes
      enabled: yes
      state: started


