---
- name: install jenkins 
  hosts: all
  become: yes
  tasks:
    - name: install java
      apt:
        name: openjdk-11-jdk
        update_cache: yes
        state: present
    - name: Add repository
      ansible.builtin.apt_key:
        url: https://pkg.jenkins.io/debian/jenkins.io.key
        state: present
    - name: Add specified repository into sources list
      ansible.builtin.command: sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
    - name: installing jenkins
      ansible.builtin.apt:
        name: jenkins
        update_cache: yes
        state: present
    - name: status check jenkins
      ansible.builtin.systemd:
        name: jenkins
        state: started 
        enabled: yes

    
    
  











sudo apt-key add -





    - name: start and enable jenkins
      systemd:
        name: jenkins.service
        enabled: yes
        state: started     