---
- name: installing wildfly on ubuntu
  hosts: all
  become: yes
  tasks: 
    - name: install java 
      ansible.builtin.apt: 
        name: openjdk-11-jdk
        update_cache: yes 
        state: present
    - name: adding group 
        ansible.builtin.group:
        name: wildfly
        state: present
    - name: adding user
      ansible.builtin.user: 
        name: wildfly
        create_home: yes
        shell: /sbin/nologin
        state: present
  - name: create a directory
    ansible.builtin.file:
      name: /tmp
      state: directory
  - name: downloading a tar file from web
    ansible.builtin.get_url:
      url: https://github.com/wildfly/wildfly/releases/download/27.0.1.Final/wildfly-27.0.1.Final.tar.gz 
      dest: /tmp
  - name: extracting file 
    ansible.builtin.unarchive:
      src: /tmp/wildfly-27.0.1.Final.tar.gz
      dest: /opt
      remote_src: yes 
  - name: Copy from tmp to opt
    ansible.builtin.copy:
      src: /opt/wildfly-27.0.1.Final
      dest: /opt/wildfly
      owner: wildfly
      group: wildfly
      remote_src: yes
  - name: changing directory ownership permissions
    ansible.builtin.file:
      path: /opt/wildfly
      owner: wildfly
      group: wildfly
      state: directory
  - name: creating directory file
    ansible.builtin.file:
      path: /etc/wildfly
      state: directory
  - name: Copy conf file with owner and permissions
    ansible.builtin.copy:
      src: /opt/wildfly/wildfly-27.0.1.Final/docs/contrib/scripts/systemd/wildfly.conf 
      dest: /etc/wildfly/
      owner: wildfly
      group: wildfly
      remote_src: yes
  - name: Copy launch file with owner and permissions
    ansible.builtin.copy:
      src: /opt/wildfly/wildfly-27.0.1.Final/docs/contrib/scripts/systemd/launch.sh
      dest: /opt/wildfly/bin/
      owner: wildfly
      group: wildfly
      remote_src: yes
  - name: executing shell command
    ansible.builtin.shell: sh -c 'chmod +x /opt/wildfly/bin/*.sh'
  - name: Copy service file
    ansible.builtin.copy:
      src: /opt/wildfly/wildfly-27.0.1.Final/docs/contrib/scripts/systemd/wildfly.service
      dest: /etc/systemd/system/
      owner: wildfly
      group: wildfly
      remote_src: yes
  - name: reload the system
    ansible.builtin.systemd:
      name: wildfly
      daemon_reload: yes
      state: started
      enabled: yes
